@echo off
REM Ersätt med dina uppgifter
set DINKASSA_USERNAME=
set DINKASSA_PASSWORD=
REM set DINKASSA_INTEGRATOR_ID=
REM set DINKASSA_MACHINE_ID=
REM set DINKASSA_MACHINE_KEY=
set BOKIO_API_TOKEN=
set BOKIO_COMPANY_ID=
set RUST_BACKTRACE=1
esbokio %*

